version: "3.9"
services:
  laravel-app:
    build:
      context: ./
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - pg-app
  pg-app:
    image: postgres:12.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "240380"
    volumes:
      - /home/PostgreSQL:/var/lib/postgresql/data
