version: "3.9"
services:
  laravel-app:
      build:
      context: ./
    ports:
      - "8080:8080"
  pg-app:
    image: postgres:12.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "240380"
    ports:
      - "5432:5432"
    volumes:
      - /home/PostgreSQL:/var/lib/postgresql/data
